#!/bin/bash
./configure --enable-roofit --enable-builtin-pcre --fail-on-missing \
            --enable-explicitlink --enable-minuit2 --enable-table \
            --enable-unuran --with-cint-maxstruct=36000 --with-cint-maxtypedef=36000 \
            --with-cint-longline=4096 --disable-castor --disable-rfio --disable-oracle
